No color in jails
Signed-off-by: Tobias Kortkamp <tobik@FreeBSD.org>

diff --git a/runit/functions b/runit/functions
--- a/runit/functions
+++ b/runit/functions
@@ -1,28 +1,47 @@
 msg() {
-    # bold
-    printf "\033[1m=> $@\033[m\n"
+	if [ -z "${JAILED}" ]; then
+		# bold
+		printf "\033[1m=> $@\033[m\n"
+	else
+		printf "=> $@\n"
+	fi
 }
 
 msg_ok() {
-    # bold/green
-    printf "\033[1m\033[32m OK\033[m\n"
+	if [ -z "${JAILED}" ]; then
+		# bold/green
+		printf "\033[1m\033[32m OK\033[m\n"
+	else
+		printf " OK\n"
+	fi
 }
 
 msg_error() {
-    # bold/red
-    printf "\033[1m\033[31mERROR: $@\033[m\n"
+	if [ -z "${JAILED}" ]; then
+		# bold/red
+		printf "\033[1m\033[31mERROR: $@\033[m\n"
+	else
+		printf "ERROR: $@\n"
+	fi
 }
 
 msg_warn() {
-    # bold/yellow
-    printf "\033[1m\033[33mWARNING: $@\033[m\n"
+	if [ -z "${JAILED}" ]; then
+		# bold/yellow
+		printf "\033[1m\033[33mWARNING: $@\033[m\n"
+	else
+		printf "WARNING: $@\n"
+	fi
 }
 
 emergency_shell() {
-    echo
-    echo "Cannot continue due to errors above, starting emergency shell."
-    echo "When ready type exit to continue booting."
-    /bin/sh -p
+	if [ -n "${JAILED}" ]; then
+		exit 1
+	fi
+	echo
+	echo "Cannot continue due to errors above, starting emergency shell."
+	echo "When ready type exit to continue booting."
+	/bin/sh -p
 }
 
 check_osver_major() {
@@ -33,7 +52,7 @@ check_osver_major() {
 }
 
 detect_jail() {
-   if [ $(sysctl -n security.jail.jailed) -eq 1 ]; then
-       export JAILED=1
-   fi
+	if [ $(sysctl -n security.jail.jailed) -eq 1 ]; then
+		export JAILED=1
+	fi
 }
